accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

inven/urls.py
from . import views
from django.urls import path

app_name = 'inventory'

urlpatterns = [
    path('add/', views.add, name='addProduct',), 
    path('add/json_call/<str:isi>/', views.ajax_call),
]

invenstory/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inven.urls')),
    path('productlist/', include('productlist.urls')),
    path('myinventory/', include('myinventory.urls')),
    path('', views.landing, name='landing'),
    path('sold/', include('terjual.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

myinventory/urls.py
from django.urls import path
from . import views

app_name = 'myinventory'

urlpatterns = [
    path('', views.inventory, name='inventory'),
    path('<int:id>/', views.inventory, name='inventory'),
    path('ajax_call/', views.ajax_call),
]

productlist/urls.py
from django.urls import path
from . import views

app_name = 'productlist'

urlpatterns = [
    path('productlist', views.productlist, name='productlist'),
    path('ajax_call/', views.ajax_call),
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    {% block style %}{% endblock %}
    <title>Invenstory </title>

</head>

<body>
    <nav class="navbar navbar-expand-lg justify-content-end" style="background-color: #e6dcc3;">
        <a class="navbar-brand" href="{% url 'landing' %}"><img src="{% static 'images/logo.png' %}" height="40" width="180"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" style="color: black;"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inventory:addProduct' %}" style="color: black; font-family: 'Montserrat', sans-serif;">add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sold" style="color: black; font-family: 'Montserrat', sans-serif;">sold</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'productlist:productlist' %}" style="color: black; font-family: 'Montserrat', sans-serif;">list</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myinventory:inventory' %}" style="color: black; font-family: 'Montserrat', sans-serif;" >inventory</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="nav-link" style="color: black; font-family: 'Montserrat', sans-serif;">log out</a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="nav-link" style="color: black; font-family: 'Montserrat', sans-serif;">log in</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:signup' %}" class="nav-link" style="color: black; font-family: 'Montserrat', sans-serif;">sign up</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block script %}{% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
<div class="container">
    <div class="row">
        <img src="{% static 'images/logo.png' %}" id="foto">
    </div>
    <div class="row">
        <div class="col-md-4 text">
            <h1 id="about">About Us</h1><br>
            <p>To make your job easier, Invenstory</p>
            <p>will help you to manage your inventory</p>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <img src="{% static 'images/foto.jpg' %}" height="350">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <h1>What we do?</h1>
        </div>
        <div class="col-md-4">
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 photos">
            <img src="{% static 'images/add.png' %}" height="130">
            <p class="kata">Add your products</p>
            <a href="{% url 'accounts:login' %}"><button class="tombol btn btn-primary">Add Products</button></a>
        </div>
        <div class="col-md-3 photos">
            <img src="{% static 'images/list.png' %}" height="130">
            <p class="kata">Calculate your sold products</p>
            <a href="{% url 'accounts:login' %}"><button class="tombol btn btn-primary">Sold Products</button></a>
        </div>
        <div class="col-md-3 photos">
            <img src="{% static 'images/sold.png' %}" height="130">
            <p class="kata">List of all your products</p>
            <a href="{% url 'accounts:login' %}"><button class="tombol btn btn-primary">List Products</button></a>
        </div>
        <div class="col-md-3 photos">
            <img src="{% static 'images/inventory.png' %}" height="130">
            <p class="kata">Restock your inventory</p>
            <a href="{% url 'accounts:login' %}"><button class="tombol btn btn-primary">Inventory</button></a>
        </div>
    </div>
</div>
{% endblock %}